config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :articles do
    resources :comments
  end
  resources :contacts
  root to: 'pages#index'
  get 'pages/about'
  #get 'name', 'pages#about' --> to assign a name to the path
  get 'pages/contact'

end
 

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :message
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @articles = Article.all
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment].permit(:body))
    @comment.user_id = current_user.id if current_user
    
    
    if @comment.save
      redirect_to article_path(@article), notice: "Your comment has been saved."
    else
      redirect_to 'new'
    end
  end
  
  def update
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    
    if @comment.update(params[:comment].permit(:body))
      redirect_to article_path(@article), notice: "Your comment has been updated."
    else
      render 'edit'
    end
  end
  
  def edit
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), notice: "Your comment has been deleted."
  end
  
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      redirect_to root_path
      name = params[:contact][:name]
      email = params[:contact][:email]
      message = params[:contact][:message]
      
      ContactMailer.contact_email(name, email, message).deliver
      flash[:success] = "Thanks. We will be in touch soon."
    else
      render pages_contact_path
      flash[:danger] = "Oops, there was a problem! Please fill out all the fields."
    end
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def index
      @articles = Article.last(4)
    end
    
    def about
    end
    
    def contact
      @contact = Contact.new
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    private
      
      def sign_up_params
        params.require(:user).permit(:email, :password, :password_confirmation, :user_name, :first_name, :last_name)
      end
      
      def account_update_params
        params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :user_name, :first_name, :last_name)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/_recent_articles.html.erb
<h4 style="text-transform: uppercase;">Recent Posts</h4>
<% @articles.each do |a| %>
  <em>Created by: <%= a.user.user_name %></em><br>
  <strong><%= link_to a.title, a %><br></strong>
  <%= truncate(a.body, :length => 80) %><br>
  <hr>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.user.user_name %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-lg-8">
    <img src="http://placehold.it/750x492"></img>
    <h1 style="font-size: 62.5px;"><%= @article.title %> </h1>
    <p class="lead">Author: <%= @article.user.user_name %></p>
    <hr>
    <p><span class="glyphicon glyphicon-time"></span> Was Posted: <%= time_ago_in_words(@article.created_at) %> ago</p>
    <hr>
    <%= @article.body %><br>
    <%= link_to 'Edit', edit_article_path(@article) %> | <%= link_to 'Back', articles_path %>
    <hr>
    <%= render 'comments/form' %><br>
    <%= render @article.comments if @article.comments.present? %><br>
  </div>
    <!-- Blog Sidebar Widgets Column -->
  <div class="col-md-4">
    <div class="well">
        <%= render 'articles/recent_articles' %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="media">
  <h4><%= comment.body %></h4>
</div>
<div class="pull-left">
  <p><%= comment.user.user_name unless comment.user.blank? %></p>
</div>
<div class="media-body">
  <p class="media-heading pull-right">
    <%= time_ago_in_words(comment.created_at) if comment.created_at %>
  </p>
  <%= comment.body %>
</div>

<%# @article.comments.present? %>
  <%= link_to "Edit", edit_article_comment_path(comment.article, comment) %>
  <%= link_to "Delete", [comment.article, comment], method: :delete, data: { confirm: "Are you sure?" } %>
<%# end %>

app/views/comments/_form.html.erb
<%= simple_form_for ([@article, @article.comments.build]) do |f| %>
  <%= f.input :body, label: "Comment" %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comment</h1>

<%= simple_form_for([@article, @comment]) do |f| %>
	<%= f.input :body %>
	<%= f.submit %>
	
	<% end %>

app/views/layouts/_flash.html.erb
<!--<p class="notice"><%#= notice %></p>-->
<!--<p class="alert"><%#= alert %></p>-->

<%= bootstrap_flash %>

app/views/layouts/_footer.html.erb
<hr>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-11">
                <ul class="list-inline">
                    <li>
                      <%= link_to "Home", root_path %>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        <%= link_to "About", pages_about_path %>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        <%= link_to "Contact", pages_contact_path %>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <% if current_user %>
                      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                    <% else %>
                      <li><%= link_to "Sign In", new_user_session_path %></li>
                    <% end %>
                </ul>
                <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
            </div>
            <div class="col-lg-1">
              <div class="footer-icons">
                <a href="http://www.bitbucket.com/megaloopy" target="_blank"><i class="fa fa-bitbucket"></i></a>
                <a href="https://www.linkedin.com/in/pedrom/" target="_blank"><i class="fa fa-linkedin"></i></a>
                <a href="https://twitter.com/Megaloopy" target="_blank"><i class="fa fa-twitter"></i></a>
              </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <strong><%= link_to "Ped's Blog", root_path, class: "navbar-brand", id: "brand" %></strong>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
        <li><%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" if !current_user %></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.user_name.upcase %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Articles", articles_path %></li>
              <li><%= link_to "Create Article", new_article_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="google" content="notranslate">
  <meta http-equiv="Content-Language" content="en">
  <title>Pedro Monsalve Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
  <div class="container">  
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/_mailer.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= simple_form_for @contact do |f| %>
        <%= f.input :name %>
        <%= f.input :email %>
        <%= f.input :message %>
        <%= f.submit "Get in touch!", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="row">
    <div class="col-lg-12 text-center">
      <h1>About Page</h1>
      <p class="lead">Test text</p>
      <ul class="list-unstyled">
          <li>List intem 1</li>
          <li>List intem 2</li>
      </ul>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="row">
    <!--<div class="col-lg-12 text-center">-->
    <!--  <h1>Contact Page</h1>-->
    <!--  <p class="lead">Test text</p>-->
    <!--  <ul class="list-unstyled">-->
    <!--      <li>List intem 1</li>-->
    <!--      <li>List intem 2</li>-->
    <!--  </ul>-->
    <!--</div>-->
    <%= render 'pages/mailer' %>
</div>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1>Welcome</h1>
  <p>To my blog where I (a noob RoR hacker) will share every resouce I come in contact with</p>
  <p><a class="btn btn-primary btn-lg">Learn more</a></p>
</div>

<!-- Page Content -->
<div class="row">
    <!-- Blog Entries Column -->
    <div class="col-md-8">

        <h1 class="page-header">
            Page Heading
            <small>Secondary Text</small>
        </h1>

        <!-- First Blog Post -->
        <h2>
            <a href="#">Blog Post Title</a>
        </h2>
        <p class="lead">
            by <a href="index.php">Start Bootstrap</a>
        </p>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
        <hr>
        <img class="img-responsive" src="http://placehold.it/900x300" alt="">
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, tempora, necessitatibus inventore nisi quam quia repellat ut tempore laborum possimus eum dicta id animi corrupti debitis ipsum officiis rerum.</p>
        <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

        <hr>

        <!-- Second Blog Post -->
        <h2>
            <a href="#">Blog Post Title</a>
        </h2>
        <p class="lead">
            by <a href="index.php">Start Bootstrap</a>
        </p>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:45 PM</p>
        <hr>
        <img class="img-responsive" src="http://placehold.it/900x300" alt="">
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam, quasi, fugiat, asperiores harum voluptatum tenetur a possimus nesciunt quod accusamus saepe tempora ipsam distinctio minima dolorum perferendis labore impedit voluptates!</p>
        <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

        <hr>

        <!-- Third Blog Post -->
        <h2>
            <a href="#">Blog Post Title</a>
        </h2>
        <p class="lead">
            by <a href="index.php">Start Bootstrap</a>
        </p>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:45 PM</p>
        <hr>
        <img class="img-responsive" src="http://placehold.it/900x300" alt="">
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, voluptates, voluptas dolore ipsam cumque quam veniam accusantium laudantium adipisci architecto itaque dicta aperiam maiores provident id incidunt autem. Magni, ratione.</p>
        <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

        <hr>

        <!-- Pager -->
        <ul class="pager">
            <li class="previous">
                <a href="#">&larr; Older</a>
            </li>
            <li class="next">
                <a href="#">Newer &rarr;</a>
            </li>
        </ul>
    </div>
    
    <div class="col-md-4">
        <!-- Side Widget Well -->
        <div class="well">
            <%= render 'articles/recent_articles' %>
        </div>
    </div>
    
</div>

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>